# Generated by Django 4.2.5 on 2023-09-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OreSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=300)),
                ("iron_content", models.FloatField()),
                ("silicon_content", models.FloatField()),
                ("aluminum_content", models.FloatField()),
                ("calcium_content", models.FloatField()),
                ("sulfur_content", models.FloatField()),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
